repos:
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.11
      stages: [commit]

-   repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: 'tests|env|docs'
      stages: [commit]

-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'poetry export -f requirements.txt --output requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]

 # -   repo: local
 #     hooks:
 #     - id: pytest
 #       name: pytest
 #       language: system
 #       entry: pytest -v -s
 #       always_run: true
 #       pass_filenames: false
 #       stages: [commit]